import { type NextPage } from "next";
import Head from "next/head";

import Timeline from "../components/Timeline";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Twitter App with T3</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Timeline where={undefined} />
      </div>
    </>
  );
};

export default Home;
